"use client";

import { Plus, CheckCircle2, Circle } from "lucide-react";
import { Modal } from "@/components/shared/Modal";
import { Button } from "@/components/shared/Button";
import { Badge } from "@/components/shared/Badge";
import { FieldLabel, inputClass } from "@/components/shared/FormField";
import { ProgressBar } from "@/components/step-erp/ProgressBar";
import SearchableSelect from "@/components/SearchableSelect";
import {
  STEP_ERP_STORES,
  STEP_ERP_TYPES,
  getStepErpType,
} from "@/lib/stepErpConfig";

const STORE_OPTIONS = STEP_ERP_STORES.map((s) => ({ value: s, label: s }));
const TYPE_OPTIONS  = STEP_ERP_TYPES.map((t) => ({ value: t.key, label: t.label }));

const OWNER_BADGE: Record<string, "info" | "purple" | "teal" | "warning"> = {
  Requester:    "info",
  Sender:       "purple",
  Receiver:     "teal",
  "Head Office":"warning",
};

interface AddEntryModalProps {
  open: boolean;
  onClose: () => void;
  typeLabel: string;
  store: string;
  erpNumber: string;
  onStoreChange: (v: string) => void;
  onErpNumberChange: (v: string) => void;
  submitting: boolean;
  onSubmit: (checked: Record<string, boolean>) => void;
  typeKey?: string;
  onTypeChange?: (v: string) => void;
  showTypeSelector?: boolean;
  // Per-step checklist state — lifted to the page so it survives together
  // with store/erpNumber, and so the page can decide what "done" means.
  checked: Record<string, boolean>;
  onToggleStep: (key: string) => void;
}

export function AddEntryModal({
  open,
  onClose,
  typeLabel,
  store,
  erpNumber,
  onStoreChange,
  onErpNumberChange,
  submitting,
  onSubmit,
  typeKey,
  onTypeChange,
  showTypeSelector = false,
  checked,
  onToggleStep,
}: AddEntryModalProps) {
  const typeDef   = getStepErpType(typeKey ?? "");
  const steps     = typeDef?.steps ?? [];
  const doneCount = steps.filter((s) => checked[s.key]).length;
  const percent   = steps.length > 0 ? Math.round((doneCount / steps.length) * 100) : 0;

  // ERP number is intentionally optional here: on some processes the number
  // only exists after a step or two is already done (e.g. it's generated by
  // the ERP itself), on others it's known up front. Store is the only thing
  // that must be filled before saving.
  const canSubmit = !!store;

  const handleClose = () => {
    onClose();
  };

  // ── Single-screen body — form fields + checklist together ──────────────────
  const body = (
    <div className="space-y-4">
      {showTypeSelector && onTypeChange && (
        <div>
          <FieldLabel required>Tipe ERP</FieldLabel>
          <SearchableSelect
            options={TYPE_OPTIONS}
            value={typeKey ?? ""}
            onChange={onTypeChange}
            placeholder="-- Pilih Tipe --"
          />
        </div>
      )}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <FieldLabel required>Store</FieldLabel>
          <SearchableSelect
            options={STORE_OPTIONS}
            value={store}
            onChange={onStoreChange}
            placeholder="-- Pilih Store --"
          />
        </div>
        <div>
          <FieldLabel>ERP Number</FieldLabel>
          <input
            type="text"
            value={erpNumber}
            onChange={(e) => onErpNumberChange(e.target.value)}
            placeholder="Boleh diisi belakangan"
            className={inputClass()}
          />
        </div>
      </div>

      {/* Preview tipe yang dipilih */}
      {typeDef && (
        <div className="rounded-xl border border-primary/10 bg-primary/5 px-4 py-3">
          <p className="text-[11px] font-semibold text-primary">{typeDef.label}</p>
          <p className="mt-0.5 text-[11px] text-gray-400">{typeDef.description}</p>
        </div>
      )}

      {typeDef && (
        <>
          {/* Progress */}
          <ProgressBar percent={percent} done={doneCount} total={steps.length} size="md" />

          {/* Tip */}
          <p className="text-[11px] text-gray-400">
            Centang langkah yang sudah kamu lakukan. ERP Number boleh diisi kapan saja — sebelum,
            di tengah, atau setelah langkah dikerjakan.
          </p>

          {/* Checklist */}
          <ul className="divide-y divide-gray-100 rounded-xl border border-gray-100">
            {steps.map((s, i) => {
              const isChecked = !!checked[s.key];
              return (
                <li key={s.key}>
                  <button
                    type="button"
                    onClick={() => onToggleStep(s.key)}
                    className={`flex w-full items-start gap-3 px-3.5 py-3 text-left transition-colors ${
                      isChecked ? "bg-green-50/60 hover:bg-green-50" : "hover:bg-gray-50"
                    }`}
                  >
                    <span className="mt-0.5 shrink-0">
                      {isChecked ? (
                        <CheckCircle2 className="h-4.5 w-4.5 text-green-500" />
                      ) : (
                        <Circle className="h-4.5 w-4.5 text-gray-300" />
                      )}
                    </span>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-baseline gap-1.5">
                        <span className="shrink-0 text-[10px] font-bold text-gray-300">
                          {i + 1}.
                        </span>
                        <p
                          className={`text-xs leading-relaxed ${
                            isChecked ? "text-gray-400 line-through" : "text-gray-700"
                          }`}
                        >
                          {s.label}
                        </p>
                      </div>
                      <Badge variant={OWNER_BADGE[s.owner] ?? "neutral"} className="mt-1">
                        {s.owner}
                      </Badge>
                    </div>
                  </button>
                </li>
              );
            })}
          </ul>
        </>
      )}
    </div>
  );

  return (
    <Modal
      open={open}
      onClose={handleClose}
      icon={Plus}
      title={showTypeSelector ? "Tambah Entry" : `Tambah ${typeLabel}`}
      description={
        typeDef
          ? `${typeDef.label} · ${doneCount}/${steps.length} langkah ditandai`
          : "Isi store dan tandai langkah yang sudah dikerjakan."
      }
      maxWidth="max-w-lg"
      footer={
        <>
          <Button variant="secondary" onClick={handleClose} disabled={submitting}>
            Batal
          </Button>
          <Button
            variant="primary"
            className="ml-auto"
            disabled={!canSubmit}
            onClick={() => onSubmit(checked)}
            loading={submitting}
          >
            {steps.length > 0
              ? doneCount === steps.length
                ? "Simpan ✓"
                : `Simpan (${doneCount}/${steps.length})`
              : "Simpan"}
          </Button>
        </>
      }
    >
      {body}
    </Modal>
  );
}